import { Product, Store } from '../types';

export const INITIAL_STORE: Store = {
  id: 'store-001',
  name: 'Corner Kirana & Mini-Mart',
  address: 'Shop #12, Market Square, Main Boulevard',
  phone: '+1 (555) 019-2834',
  tax_rate: 0.05, // 5% tax
  currency_symbol: '$',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    store_id: 'store-001',
    name: 'Super Basmati Rice',
    barcode: '8901234567890',
    category: 'Staples & Grains',
    unit_type: 'weight_kg',
    price: 2.80, // per kg
    cost: 1.90,
    stock_quantity: 120.500,
    low_stock_threshold: 20.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    store_id: 'store-001',
    name: 'Whole Wheat Chakki Atta',
    barcode: '8901234567891',
    category: 'Staples & Grains',
    unit_type: 'weight_kg',
    price: 1.20,
    cost: 0.85,
    stock_quantity: 85.000,
    low_stock_threshold: 15.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    store_id: 'store-001',
    name: 'Granulated White Sugar',
    barcode: '8901234567892',
    category: 'Staples & Grains',
    unit_type: 'weight_kg',
    price: 1.40,
    cost: 1.00,
    stock_quantity: 45.000,
    low_stock_threshold: 10.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    store_id: 'store-001',
    name: 'Fresh Red Onions',
    barcode: null, // Non-barcoded weight item
    category: 'Produce & Vegetables',
    unit_type: 'weight_kg',
    price: 1.50,
    cost: 0.90,
    stock_quantity: 12.400, // Low stock trigger
    low_stock_threshold: 15.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    store_id: 'store-001',
    name: 'Fresh Ripe Tomatoes',
    barcode: null, // Non-barcoded weight item
    category: 'Produce & Vegetables',
    unit_type: 'weight_kg',
    price: 2.20,
    cost: 1.30,
    stock_quantity: 8.200, // Low stock trigger
    low_stock_threshold: 10.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    store_id: 'store-001',
    name: 'Golden Yukon Potatoes',
    barcode: null,
    category: 'Produce & Vegetables',
    unit_type: 'weight_kg',
    price: 1.10,
    cost: 0.65,
    stock_quantity: 65.000,
    low_stock_threshold: 20.000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    store_id: 'store-001',
    name: 'Full Cream Milk 1L',
    barcode: '8901234567893',
    category: 'Dairy & Bakery',
    unit_type: 'each',
    price: 1.80,
    cost: 1.35,
    stock_quantity: 32,
    low_stock_threshold: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    store_id: 'store-001',
    name: 'Farm Fresh Eggs (Dozen)',
    barcode: '8901234567894',
    category: 'Dairy & Bakery',
    unit_type: 'each',
    price: 3.20,
    cost: 2.40,
    stock_quantity: 4, // Critical low stock
    low_stock_threshold: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    store_id: 'store-001',
    name: 'Artisan Sandwich Bread 500g',
    barcode: '8901234567895',
    category: 'Dairy & Bakery',
    unit_type: 'each',
    price: 1.60,
    cost: 1.10,
    stock_quantity: 14,
    low_stock_threshold: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-010',
    store_id: 'store-001',
    name: 'Pure Sunflower Cooking Oil 1L',
    barcode: '8901234567896',
    category: 'Spices & Condiments',
    unit_type: 'each',
    price: 4.50,
    cost: 3.40,
    stock_quantity: 28,
    low_stock_threshold: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    store_id: 'store-001',
    name: 'Red Chilli Powder 200g',
    barcode: '8901234567897',
    category: 'Spices & Condiments',
    unit_type: 'each',
    price: 2.10,
    cost: 1.20,
    stock_quantity: 18,
    low_stock_threshold: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    store_id: 'store-001',
    name: 'Premium Black Tea 250g',
    barcode: '8901234567898',
    category: 'Beverages & Tea',
    unit_type: 'each',
    price: 3.80,
    cost: 2.70,
    stock_quantity: 22,
    low_stock_threshold: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
